apply_rename:
  name: Apply Rename
  description: Rename a Home Assistant entity.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to rename.
      required: true
      example: "light.living_room"
      selector:
        entity: {}
    new_name:
      name: New Name
      description: The new name for the entity.
      required: true
      example: "Living Room Ceiling Light"
      selector:
        text: {}
