apply_rename:
  name: Apply Rename
  description: Rename a Home Assistant entity.
  fields:
    entity_id:
      name: Entity ID
      description: The entity ID to rename.
      required: true
      example: "light.living_room"
      selector:
        entity: {}
    new_entity_id:
      name: New Entity ID
      description: The new entity ID.
      required: true
      example: "light.lr_ceiling_light"
      selector:
        text: {}
    new_name:
      name: New Name
      description: Optional friendly name to apply.
      required: false
      example: "LR Ceiling Light"
      selector:
        text: {}
