name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Update version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"  # Remove 'v' prefix if present
          # Update version in manifest.json
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" custom_components/entity_renamer/manifest.json
          # Update version in setup.py
          sed -i "s/version=\"[^\"]*\"/version=\"$VERSION\"/" setup.py
          # Update version in version.json
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" version.json

      - name: Create zip
        run: |
          mkdir -p /tmp/ai-entity-renamer
          cp -r custom_components /tmp/ai-entity-renamer/
          cd /tmp
          zip -r ai-entity-renamer.zip ai-entity-renamer

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/ai-entity-renamer.zip
          asset_name: ai-entity-renamer.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Build and publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m pip install build twine
          python -m build
          twine upload dist/*
